name: hdb_data_pipeline

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed  
      - name: Install Chrome
        run: |
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo apt install -y ./google-chrome-stable_current_amd64.deb
              sudo apt install -f
              google-chrome --version

      - name: Install Matching ChromeDriver
        run: |

          
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win64/chromedriver-win64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver          

          

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: execute py script # run web_scrapper.py
        run: python web_scrapper.py
