name: hdb_data_pipeline

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed  
      - name: download chrome engine
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true
    
          

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: execute py script # run web_scrapper.py
        run: python web_scrapper.py
        
      - name: Commit report
        run: |
          git config --global user.name 'Vibu'
          git config --global user.email 'vibumy@gmail.com'
          git commit -am "Automated report"
          git push
